name : git hub push to s3 oidc 
on :
    push :
        branches : 
             - main 

permissions :
    id-token : write 
    contents : read 

jobs :
    deploy :
        runs-on : ubuntu-latest

        steps :

            - name : checkout 
              uses : actions/checkout@v4
            - name : configure aws
              uses : aws-actions/configure_aws_credentials@v4
              with : 
                role-to-assume : arn:aws:iam::316704942911:role/github_to_s3
                aws-region : us-east-1
            - name : upload html file 
              run : |
                  echo "uploading html file to s3 "
                  aws s3 cp index.html s3://316704942911/index.html
                






